add usecase
darwinia-network/darwinia.js-1.0-deprecated pull request #56
Opened 2022-03-21 04:58 UTC by cinlk

Merge darwinia-js-usecase

2022-03-21 05:05 UTC, WoeOm approved these changes

2022-03-21 05:23 UTC, sxlwar requested changes

2022-03-21 05:23 UTC, sxlwar commented on example/blockInfo.js
> +};
貌似就是
```js
const darwiniaTypesBundle = typesBundleForPolkadotApps;
```

darwiniaTypesBundle 这个应该是多余的

2022-03-21 05:23 UTC, sxlwar commented on example/checkAddress.js
> +
用 const 吧，其它文件里好像都是 const

2022-03-21 05:23 UTC, sxlwar commented on example/transfer.js
> +  spec: {
这里也是

2022-03-21 05:23 UTC, sxlwar commented on example/transferBatch.js
> +  spec: {
here

2022-03-21 06:43 UTC, cinlk commented on example/blockInfo.js
> +};
done

2022-03-21 06:43 UTC, cinlk commented on example/transfer.js
> +  spec: {
done

2022-03-21 06:43 UTC, cinlk commented on example/transferBatch.js
> +  spec: {
done

2022-03-22 03:08 UTC, sxlwar approved these changes

2022-03-22 03:09 UTC, merged