Api derive
darwinia-network/darwinia.js-1.0-deprecated pull request #57
Opened 2022-03-24 03:56 UTC by cinlk

migrate api-derive from apps

2022-03-24 04:30 UTC, sxlwar requested changes

2022-03-24 04:30 UTC, sxlwar commented on packages/api-derive/src/staking/query.ts
> +      return (api.query.staking.erasStakers ? retrieveCurr(api, stashId) : retrievePrev(api, stashId)).pipe(
Help to confirm whether the `api.query.staking.erasStakers` method always exists? In that case, the logic here could be more streamlined. @WoeOm @AurevoirXavier 
<img width="988" alt="image" src="https://user-images.githubusercontent.com/20088392/159841082-d49348eb-bd3f-4358-847b-bad117d461cd.png">

2022-03-24 04:30 UTC, sxlwar commented on packages/api-derive/src/staking/query.ts
> +    ? api.query.staking.ledger(controllerId).pipe(
The same as Line 117

2022-03-24 04:30 UTC, sxlwar commented on packages/api-derive/src/staking/query.ts
> +
Need to evaluate these disabled eslint rules. Whether the errors suggested by these rules are real or not

Check other files as well

2022-03-24 07:25 UTC, cinlk commented on packages/api-derive/src/staking/query.ts
> +
> Need to evaluate these disabled eslint rules. Whether the errors suggested by these rules are real or not
> 
> Check other files as well

I  have try to remove those "eslint-disable" comments for entire file at each of api-derive project files,  and then executing the command "tsc --emitDeclarationOnly --outdir ./build" successfully compile files.

2022-03-28 03:01 UTC, AurevoirXavier commented on packages/api-derive/src/staking/query.ts
> +      return (api.query.staking.erasStakers ? retrieveCurr(api, stashId) : retrievePrev(api, stashId)).pipe(
I'm don't know if they will change the API in the future.

But it still exists in Polkadot v0.9.18.

2022-03-28 03:04 UTC, AurevoirXavier commented on packages/api-derive/src/staking/query.ts
> +      return (api.query.staking.erasStakers ? retrieveCurr(api, stashId) : retrievePrev(api, stashId)).pipe(
I'm don't know if they will change the API in the future.

But it still exists in Polkadot v0.9.18.

2022-03-28 03:04 UTC, AurevoirXavier commented on packages/api-derive/src/staking/query.ts
> +    ? api.query.staking.ledger(controllerId).pipe(
Same.

2022-03-28 08:44 UTC, WoeOm approved these changes

2022-03-29 01:36 UTC, merged