add account in derive
darwinia-network/darwinia.js-1.0-deprecated pull request #64
Opened 2022-04-14 01:29 UTC by cinlk

2022-04-14 01:41 UTC, sxlwar requested changes

2022-04-14 01:41 UTC, sxlwar commented on packages/api-derive/src/accounts/account.ts
> +  return api.query.system.account(accountId).pipe(
I think that some computational logic missing here.  Pls check the screenshot at https://github.com/darwinia-network/wormhole-ui/issues/142

2022-04-14 02:56 UTC, cinlk commented on packages/api-derive/src/accounts/account.ts
> +  return api.query.system.account(accountId).pipe(
I test the system.account locally  for example:
```
api.query.system
        .account(address)
        .then((res) => {
          console.log(`  balance ${res} `);
        })
```
the response data struct is {"nonce":4,"consumers":0,"providers":1,"sufficients":0,"data":{"free":7766680000000,"reserved":0,"freeKton":0,"reservedKton":0}} and all balance are correct.

2022-04-20 02:19 UTC, HackFisher requested changes

2022-04-20 02:19 UTC, HackFisher commented on packages/api-derive/src/accounts/usableAccount.ts
> +export function usableAccount (instanceId: string, api: ApiInterfaceRx): (tokenType: u8 | AnyNumber | Uint8Array, accountId: AccountId | string | Uint8Array) => Observable<DeriveUsableAccount> {
bad naming? should be `usable_balance`?

2022-04-20 02:19 UTC, HackFisher commented on packages/api-derive/src/accounts/usableAccount.ts
> +        return { usableBalance: free };
Is this implementation correct?

2022-04-20 02:20 UTC, HackFisher commented
@AurevoirXavier @AsceticBear please help review the logic of the implmentation.

2022-04-20 02:57 UTC, cinlk commented on packages/api-derive/src/accounts/usableAccount.ts
> +        return { usableBalance: free };
yes, the "system.account" querying could fetch  our customized account data.
this is the data type reference. 
https://github.com/darwinia-network/darwinia.js/blob/master/packages/types/src/interfaces/darwiniaInject/types.ts#L14

2022-04-20 03:06 UTC, cinlk commented on packages/api-derive/src/accounts/usableAccount.ts
> +export function usableAccount (instanceId: string, api: ApiInterfaceRx): (tokenType: u8 | AnyNumber | Uint8Array, accountId: AccountId | string | Uint8Array) => Observable<DeriveUsableAccount> {
I think it should be Camel-Case cause  polkadot-js use Camel-Case rule  for function name. 
the original generated rpc api also use Camel-Case, please refer this link:
https://github.com/darwinia-network/darwinia.js/blob/60a812bc07153c99d080858d83957dea0713d534/packages/types/src/interfaces/augment-api-rpc.ts#L78

2022-04-20 03:33 UTC, AsceticBear commented on packages/api-derive/src/feeMarket/types.ts
> +export interface DeriveMarketFee{
```suggestion
export interface DeriveMarketFee {
```

2022-04-20 03:33 UTC, AsceticBear commented on packages/api-derive/src/feeMarket/marketFee.ts
> +function lastmarkerFee (api: ApiInterfaceRx) : Observable<DeriveMarketFee | undefined> {
```suggestion
function lastAssignedRelayerFee (api: ApiInterfaceRx) : Observable<DeriveMarketFee | undefined> {
```

2022-05-05 02:27 UTC, HackFisher commented on packages/api-derive/src/accounts/usableAccount.ts
> +        return { usableBalance: free };
https://github.com/darwinia-network/darwinia-common/blob/12cb3d1da3bc53a748b785691b4a7bd3e4c630ae/frame/balances/src/lib.rs#L1956

2022-05-05 02:28 UTC, HackFisher commented on packages/api-derive/src/accounts/usableAccount.ts
> +        return { usableBalance: free };
```
			fn usable(
				&self,
				reasons: darwinia_support::balance::LockReasons,
				frozen_balance: darwinia_support::balance::FrozenBalance<$btype>,
			) -> $btype {
				self.free.saturating_sub(frozen_balance.frozen_for(reasons))
			}
```

2022-05-11 02:45 UTC, sxlwar requested changes

2022-05-11 02:45 UTC, sxlwar commented on packages/api-derive/src/feeMarket/marketFee.ts
> +
name should be data without 's'

2022-05-11 02:45 UTC, sxlwar commented on packages/types/src/mix/index.ts
> +  // AccountData: {
remove meaningless comments pls

2022-05-11 02:45 UTC, sxlwar commented on packages/api-derive/src/accounts/usableAccount.ts
> +  if (tokenType !== 0 && tokenType !== 1) {
we can use a more meaningful variable to replace the numbers here, otherwise, always need to think about the number meaning, ring or kton

suggestion: enum

2022-05-11 02:45 UTC, sxlwar commented on packages/api-derive/src/accounts/usableAccount.ts
> +        balanceFree = free;
1. use more direct conditional judgment
```
if (!item.reasons.isFee) {
    maxlock = bnMax(item.amount, maxlock);
}
```

2. maxlock will be assigned the last value that satisfies the condition, does this here we expect? If it is expected, we can use 'find' to avoid redundant loop
some thing like: 
```
const target = ktonLocks.reverse().find(item => !item.reason.isFee);
... 
```

2022-05-11 03:16 UTC, cinlk commented on packages/types/src/mix/index.ts
> +  // AccountData: {
I misunderstand this part of polkadotCompatibleTypes. as @WoeOm  said it  could be  compatible with  some situations   using polkadot original types. at not don't need to remove.

2022-05-11 03:56 UTC, cinlk commented on packages/api-derive/src/accounts/usableAccount.ts
> +        balanceFree = free;
It's not a sorted array, I find max locked balance According to runtime fronzen-balance as below:

```
fn frozen_balance(who: impl Borrow<T::AccountId>) -> FrozenBalance<T::Balance> {
			let mut frozen_balance = <FrozenBalance<T::Balance>>::zero();
			for lock in Self::locks(who.borrow()).iter() {
				let locked_amount = lock.amount;

				if lock.reasons == Reasons::All || lock.reasons == Reasons::Misc {
					frozen_balance.misc = frozen_balance.misc.max(locked_amount);
				}
				if lock.reasons == Reasons::All || lock.reasons == Reasons::Fee {
					frozen_balance.fee = frozen_balance.fee.max(locked_amount);
				}
			}

			frozen_balance
		}
```

2022-05-19 06:55 UTC, sxlwar approved these changes

2022-05-19 07:00 UTC, closed without merging

2022-05-19 07:01 UTC, cinlk commented
forward to  https://github.com/darwinia-network/darwinia.js/pull/71