update polkadot version and types
darwinia-network/darwinia.js-1.0-deprecated pull request #88
Opened 2022-07-11 06:07 UTC by cinlk

2022-07-11 07:20 UTC, sxlwar requested changes

2022-07-11 07:20 UTC, sxlwar commented on packages/types/src/mix/utils.ts
> +function typesFromDefinitions(
lint error

2022-07-11 10:51 UTC, JayJay1024 approved these changes

2022-07-14 02:29 UTC, sxlwar commented
建议还是不要忽略 lint，可以避免一些语法可能导致的bug

2022-07-14 02:30 UTC, sxlwar approved these changes

2022-07-14 02:30 UTC, merged